### ISSUE TITLE
Questions about the unstable training

### ISSUE THREAD

**Issue by ma-xu** [UCSC-VLAA/RobustCNN#1]
Thanks for your great work.

I have a question about "we empirically find using too large kernel size (e.g., 11×11) can lead to unstable training" in Section 5. 

What do you mean by unstable training? Does that mean the peformances on ImageNet-1K vary a lot when training mutiple times?

**Comment by zw615** [comment]
Yes, for the inverted block (4x hidden dim), we find using kernel_size=11 often leads to larger variation, and degraded performance compared to kernel_size=7

**Comment by ma-xu** [comment]
Thanks for your explanation.
